# Generated by Django 2.2.5 on 2020-02-10 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=3)),
                ('x_coord', models.DecimalField(decimal_places=16, max_digits=22)),
                ('y_coord', models.DecimalField(decimal_places=16, max_digits=22)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
