# Generated by Django 2.2.5 on 2020-02-10 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vishnu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='x_coord',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='y_coord',
            new_name='long',
        ),
    ]
