# Generated by Django 2.2.5 on 2020-02-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vishnu', '0002_auto_20200210_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='file',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
