# Generated by Django 2.2.5 on 2020-03-11 05:55
import pytz
import string
import random
import datetime
from django.db import migrations, models


def add_existing_users_to_userauth(apps, _):
    """Every user must have a row in UserAuth"""

    User = apps.get_model("auth", "User")
    UserAuth = apps.get_model("vishnu", "UserAuth")

    users = User.objects.all()

    for user in users:
        user_auth, is_newly_created = UserAuth.objects.get_or_create(user=user)

        if is_newly_created:

            # Generate pseudo token and expiry
            token = ''.join(random.choice(string.ascii_letters + string.digits)
                            for i in range(64))
            EXPIRES_IN = 1  # minute
            expires_in_datetime = datetime.timedelta(minutes=int(EXPIRES_IN))
            expiry = expires_in_datetime + datetime.datetime.now(tz=pytz.UTC)

            # Save token and expiry
            user_auth.token = token
            user_auth.expiry = expiry
            user_auth.save()


class Migration(migrations.Migration):

    dependencies = [
        ('vishnu', '0005_userauth'),
    ]

    operations = [
        migrations.RunPython(add_existing_users_to_userauth),
    ]
